### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by afonsopacifer** [afonsopacifer/css-da-vinci#1]
# Backlog
- [ ] texts - **Core feature**
- [ ] rotate - **Core feature**
- [ ] gradient - **Core feature**
- [ ] background position e repeat - **Core feature**
- [ ] Autoprefixer - **Build update**
- [ ] Website #2 - **Docs**
- [ ] Refactor all variables and arguments names - **Core update**
# Doing

![l-death-note-ztpMY1t5VYWlO](https://camo.githubusercontent.com/79bd56223ae68d9a2ab2c5a82e53a2d798c0e275/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f7a74704d593174355659576c4f2f67697068792e676966)
# Done
#### Tasks for Release 0.4.0
- [x] Regression testing - **Test**
  - [x] Create files for test - **Test**
  - [x] Create Grunt tasks for files - **Test**
  - [x] Add BackstopJS - **Test**
  - [x] package.json (Add dependencies and configure npm task) - **Test**
  - [x] Configure backstop.json - **Test**
  - [x] Add autoprefixer for phantonJS webkit support - **Build update**
  - [x] Document all steps for testing - **Docs**  
- [x] travis CI (lint) - **Test**
- [x] travis CI badge
- [x] Describe the new functions - **Docs**  
  - [x] **Edit**
    - [x] shadow() (drop-shadow > box-shadow)
- [x] Create all functions - **Core**
  - [x] **Edit**
    - [x] shadow() (drop-shadow > box-shadow)
- [x] Lint and refactor - **Core**
- [x] Write regression tests - **Core**
- [x] Add images and refactor - **Docs**
- [x] Fix flip anchor  and class name (.picture > .element) in readme - **Docs**
- [x] Add markup (commented) in plankton demo. 
- [x] Update version and release in all files
#### Tasks for Release 0.3.0

**Pixel Art  - Enhancement**
- [x] Describe the new functions - **Docs**
  - [x] origin()  
  - [x] line()
  - [x] lineX()
  - [x] lineY()
- [x] Create all functions - **Core**
  - [x] origin()  
  - [x] line()
  - [x] lineX()
  - [x] lineY()
- [x] Update grid() (add position: relative;) - **Core**
- [x] Lint and refactor - **Core**
- [x] Add images and refactor - **Docs**

**Images - New feature**
- [x] Describe the new functions - **Docs**
- [x] Create **img**  function - **Core**
- [x] Lint and refactor - **Core**
- [x] Add images and refactor - **Docs**
- [x] Update version and release in all files
#### Tasks for Release 0.2.0 - Pixel Art support
- [x] Describe the new functions - **Docs**
- [x] Create **pixels** and **p** function - **Core**
- [x] Create **grid** function - **Core**
- [x] Lint and refactor - **Core**
- [x] Create a DEMO
- [x] Add images and refactor - **Docs**
- [x] Update version and release in all files
#### Tasks for Release 0.1.0
- [x] Basic Files
- [x] Basic Docs
- [x] Create a da-vinci.styl file (follow the basic docs)
- [x] Update Basic Docs (add px / elemento > element / add default values)
- [x] Create a demo page
- [x] Add image exemples in readme.md
- [x] Add build process with Grunt ot Gulp
  - [x] Compile
  - [x] Lint
  - [x] Live reload
